[default.extend-words]
thur = "thur"
numer = "numer"
HD = "HD"
hd = "hd"
passin = 'passin'

# defined in database schema
lastest = "lastest"

[files]
extend-exclude = ["CHANGELOG.md", "**/migrations/*.ts", "**/fr.{ts,json}", "**/es.{ts,json}"]
