export enum MainActions {
  UpdateMnemonic,
  UpdateTempWallet,
  CreateWallet,
  DeleteWallet,
  ImportWallet,
  ExportWallet,
  GetTransaction,
  GetTransactions,
  SetPage,
  SaveNetworks,
  DeleteNetwork,
  ErrorMessage,
  SetDialog,
  AddItemInTransfer,
  RemoveItemInTransfer,
  UpdateItemInTransfer,
  UpdateTransfer,
  UpdatePassword,
  UpdateLoading,
  Networks,
  Wallet,
}

export default MainActions
