# Public sandbox configuration from SSL.com's official action:
# https://github.com/SSLcom/esigner-codesign/blob/b7f8ff36fc0de8690fbbab8e5b4421d29802f747/src/config.ts
CLIENT_ID=qOUeZCCzSqgA93acB3LYq6lBNjgZdiOxQc-KayC3UMw
OAUTH2_ENDPOINT=https://oauth-sandbox.ssl.com/oauth2/token
CSC_API_ENDPOINT=https://cs-try.ssl.com
TSA_URL=http://ts.ssl.com
TSA_LEGACY_URL=http://ts.ssl.com/legacy
