name: Checksums of release draft

on:
  workflow_run:
    workflows:
      - Package Neuron for Release Draft
    types:
      - completed

jobs:
  checksums:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Download binaries
        run: |
          mkdir -p /tmp/Neuron
          node ./scripts/download-binaries-from-release-draft.js /tmp/Neuron
        shell: pwsh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Checksums
        run: node ./scripts/generate-checksum-table.js /tmp/Neuron
        shell: pwsh
