name: Playwright Tests
on:
  - pull_request
  - push
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Lerna
      run: yarn global add lerna
    - name: Install dependencies
      run: yarn
    - name: download binary
      run: ./scripts/download-ckb.sh mac
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build main
      run: yarn build:main
    - name: Run Playwright tests
      run: yarn test:e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: packages/e2e/test-results
        retention-days: 30
